services:
  derpic:
    build:
      context: .
      target: final
    restart: unless-stopped
    ports:
      - 3891:3000
    environment:
      DERPIC_DATABASE_URL: "postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}?sslmode=disable"
      DERPIC_ADMIN_TOKEN: ${DERPIC_ADMIN_TOKEN}
      DERPIC_PUBLIC_BASE_URL: ${DERPIC_PUBLIC_BASE_URL}
      RUST_LOG: ${RUST_LOG:-info}
  derpic_postgres:
    image: postgres:16
    ports: [ "5432:5432" ]
    restart: unless-stopped
    volumes: [ "./pgdata:/var/lib/postgresql/data" ]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
