services:
  derpic_postgres:
    image: postgres:16
    ports: [ "5432:5432" ]
    restart: unless-stopped
    volumes: [ "./pgdata:/var/lib/postgresql/data" ]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
